import { createServer } from 'node:http';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { browser, pause } from './browser.mjs';
import { entries, errors, snapshot } from './fixtures.mjs';
import { buildContext } from '../format.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));
const allowed = new Set(['panel.html', 'panel.css', 'panel.js', 'filters.js', 'format.js', 'redact.js', 'inspector.js']);
const server = createServer((req, res) => {
  const name = new URL(req.url, 'http://localhost').pathname.slice(1);
  if (!allowed.has(name)) { res.writeHead(404); res.end(); return; }
  res.setHeader('Content-Type', name.endsWith('.js') ? 'text/javascript' : name.endsWith('.css') ? 'text/css' : 'text/html');
  res.setHeader('Content-Security-Policy', manifest.content_security_policy.extension_pages);
  res.end(readFileSync(join(root, name)));
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let chrome;
try {
  chrome = await browser();
  const { send, attach, evaluate } = chrome;
  const target = await send('Target.createTarget', { url: 'about:blank' });
  const session = await attach(target.targetId);
  await send('Page.enable', {}, session);
  await send('Runtime.enable', {}, session);
  const source = `(() => {
    const data = ${JSON.stringify({ entries, errors, snapshot })};
    const subscribers = new Set();
    window.chrome = { devtools: {}, runtime: { getManifest: () => ({version: ${JSON.stringify(manifest.version)}}) } };
    window.contextStore = { ...data, generation: 0, paused: false, pageContext: true,
      status: 'Synthetic preview · optional page context enabled',
      subscribe(fn) { subscribers.add(fn); return () => subscribers.delete(fn); },
      clear() { this.entries = []; this.errors = []; this.generation++; for (const fn of subscribers) fn(); },
      togglePause() { this.paused = !this.paused; for (const fn of subscribers) fn(); },
      setPageContext(value) { this.pageContext = value; this.clear(); }
    };
    document.execCommand = () => true;
  })();`;
  await send('Page.addScriptToEvaluateOnNewDocument', { source }, session);
  await send('Emulation.setDeviceMetricsOverride', { width: 1100, height: 880, deviceScaleFactor: 1, mobile: false }, session);
  await send('Page.navigate', { url: `http://127.0.0.1:${server.address().port}/panel.html` }, session);
  for (let n = 0; n < 60; n++) {
    if (await evaluate(session, `document.querySelectorAll('.request-row').length === 6`)) break;
    await pause(100);
  }
  assert.equal(await evaluate(session, `document.querySelectorAll('.request-row').length`), 6,
    JSON.stringify(await evaluate(session, `({ready:document.readyState, fixture:!!window.contextStore, chrome:!!window.chrome?.devtools, status:document.getElementById('capture-state')?.textContent})`)));
  await evaluate(session, `document.querySelector('[data-id="3"]').click();document.getElementById('tab-response').click()`);
  assert.match(await evaluate(session, `document.getElementById('inspector').textContent`), /Quantity must be greater than zero/);
  assert.ok(!(await evaluate(session, `document.getElementById('inspector').textContent`)).includes('demo@example.test'));
  mkdirSync(join(root, 'docs/images'), { recursive: true });
  async function screenshot(name) {
    await pause(100);
    const shot = await send('Page.captureScreenshot', { format: 'png' }, session);
    const bytes = Buffer.from(shot.data, 'base64');
    writeFileSync(join(root, 'docs/images', name + '.png'), bytes);
    writeFileSync(join(root, 'docs/images', name + '-graphite.png'), bytes);
  }
  await screenshot('preview');
  await evaluate(session, `document.querySelector('[data-view="brief"]').click()`);
  await screenshot('markdown');
  await send('Emulation.setDeviceMetricsOverride', { width: 680, height: 950, deviceScaleFactor: 1, mobile: false }, session);
  await evaluate(session, `document.querySelector('[data-view="requests"]').click();document.getElementById('tab-response').click()`);
  await screenshot('docked');
  assert.equal(await evaluate(session, 'document.documentElement.scrollWidth <= innerWidth'), true);
  const report = buildContext(entries[2], errors);
  for (const secret of ['demo@example.test', 'demo-request-secret', 'demo-storage-secret']) assert.ok(!report.includes(secret));
  writeFileSync(join(root, 'docs/EXAMPLE.md'), '<!-- Generated by scripts/preview.mjs from fictional fixtures only. -->\n\n' + report);
  console.log('Generated three synthetic previews and the example report using the shipped UI and formatter.');
} finally {
  if (chrome) await chrome.close();
  await new Promise(resolve => server.close(resolve));
}
